lmsproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from lcapiapp.views import *

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("umapp.urls")),
    path('', include("lmsapp.urls")),

    path('api/v1/customer/', include("lcapiapp.urls")),
    path('api/v1/logistics/', include("lbapiapp.urls")),

    # path('password-reset/check/token/<uidb64>/<token>/',
    #      PasswordTokenCheckAPI.as_view(), name='token-check'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

umapp/urls.py
from django.urls import path, include
from .views import *

app_name = "umapp"
urlpatterns = [
    
#     path("operator/reset-password/",
#          LogisticsAdminResetPasswordView.as_view(), name="laresetpassword"),
    # path("operator/login/", LogisticsAdminLoginView.as_view(),
    #      name="logisticsadminlogin"),
    


    # Country
    path('operator/country/create',
         CountryCreateView.as_view(), name='countrycreate'),
    path('operator/country/<int:pk>/edit/',
         CountryUpdateView.as_view(), name='countryedit'),


    # province
    # path('operator/province/list/', ProvinceView.as_view(), name='provincelist'),
    path('operator/province/create/',
         ProvinceCreateView.as_view(), name='provincecreate'),
    path('operator/province/<int:pk>/edit/',
         ProvinceUpdateView.as_view(), name='provinceedit'),
    path('operator/province/delete/<int:pk>/',
         ProvinceDelete.as_view(), name='provincedelete'),


    # #District url
    # path('operator/district/list/', DistrictView.as_view(), name="districtlist"),
    path('operator/district/create/',
         DistrictCreateView.as_view(), name="districtcreate"),
    path('operator/district/update/<int:pk>/',
         DistrictUpdate.as_view(), name="districtedit"),


    # #City Url
    # path('operator/cities/list/',CityView.as_view(), name='citylist'),
    path('operator/cities/create/', CityCreateView.as_view(), name='citycreate'),
    path('operator/city/update/<int:pk>/',
         CityUpdateView.as_view(), name="cityedit"),

     path("initial-setup/", InitialSetupView.as_view(), name="initialsetup"),


    # branchoperator
    path('operator/branch-operator/list',
         BranchOperatorListView.as_view(), name='operatorlist'),
    path('operator/branch-operator/create',
         BranchOperatorCreateView.as_view(), name='operatorcreate'),
    path('operator/branch-operator/update/<int:pk>',
         BranchOperatorUpdateView.as_view(), name='operatorupdate'),


    # Branch operator password change
    path('operator/branch-operator/pass/change/<int:pk>/',
         BranchOperatorPasswordChangeView.as_view(), name='operatorpasschange'),



    # Shipping Zone
    path('operator/branch-operator/shipping/zone/',
         LogisticBranchShippingListZoneView.as_view(), name='shippinglist'),
    path('operator/branch-operator/shipping/zone/create',
         LogisticBranchShippingZoneCreateView.as_view(), name='shippingzonecreate'),
    path('operator/branch-operator/shipping/zone/update/<int:pk>/',
         LogisticBranchShippingZoneUpdateView.as_view(), name='shippingupdate'),
    path('operator/branch-operator/shipping/zone/detail/<int:pk>/',
         logisticsBranchShippingZoneDetailView.as_view(), name='shippingdetail'),
     path('operator/ajax/serch/city/', AjaxCitySearchView.as_view(), name = 'ajaxcitysearach'),
     # path('operator/ajax/list/city/', AjaxCitySearchListView.as_view(), name = 'ajaxcitysearchlist'),


    # DeliveryType/

    path('operator/branch-operator/create/deliverytype/',
         DeliveryTypeView.as_view(), name='deliverytype'),
    path('operator/branch-operator/update/deliverytype/<int:pk>/',
         DeliveryTypeUpdateView.as_view(), name='deliverytypeupdate'),

     #settings
    path('operator/branch-operator/settings/',
         SettingView.as_view(), name='settings'),
     path('operator/branch-operator/settings/ajax/search/city/', AjaxSettingsCitySearchView.as_view(), name = 'ajaxsettingscitysearch'),
     # path('operator/branch-operator/settings/ajax/search/district/', AjaxSettingsDistrictSearchView.as_view(), name = 'ajaxsettingsdistrictsearch'),
     # path('operator/branch-operator/settings/ajax/search/province/', AjaxSettingsProvinceSearchView.as_view(), name = 'ajaxsettingsprovincesearch'),
     # path('operator/branch-operator/settings/ajax/search/country/', AjaxSettingsCountrySearchView.as_view(), name = 'ajaxsettingscountrysearch'),
     


    # ajax
    path('operator/branch-operator/email/validate/',
         validateoperatoremailview, name='checkemail'),

    path('countryname/check/', CountryAjaxCheck, name='checkcountryname'),
    path('provincename/check/', ProvinceAjaxCheck, name='checkprovincename'),
    path('districtname/check/', DistrictAjaxCheck, name='checkdistrictname'),
    path('cityname/check/', CityAjaxCheck, name='checkcityname'),

    # operator customer
    path('operator/customers/list/',
         OperatorCustomersListView.as_view(), name='opcustomerslist'),
    path('operator/customers/create/',
         OperatorCustomersCreateView.as_view(), name='opcustomerscreate'),
    path('operator/customers/update/<int:pk>/',
         OperatorCustomersUpdateView.as_view(), name='opcustomersupdate'),
    path('operator/customers/change-password/<int:pk>',
         OperatorCustomersPasswordChangeView.as_view(), name='opcustomerspc'),
    path('operator/customers/detail/<int:pk>/',
         OperatorCustomersDetailView.as_view(), name='opcustomersdetail'),
    path('operator/customers/payment-list/',
         LogisticAdminLogisticsCustomerPaymentListView.as_view(), name="lalcpaymentlist"),


     # operator rider
     path('operator/deliveryperson/list/',
         OperatorDeliveryPersonListView.as_view(), name='opdeliverypersonlist'),
     path('operator/deliveryperson/create/',
         OperatorDeliveryPersonCreateView.as_view(), name='opdeliverypersoncreate'),
     path('operator/deliveryperson/detail/<int:pk>/',
         OperatorDeliveryPersonDetailView.as_view(), name='opdeliverypersondetail'),
     path('operator/deliveryperson/update/<int:pk>/',
         OperatorDeliveryPersonUpdateView.as_view(), name='opdeliverypersonupdate'),
     path('operator/deliveryperson/change-password/<int:pk>',
         OperatorDeliveryPersonPasswordChangeView.as_view(), name='opdeliverypersonpc'),
     



    #Customer signup/login
    path("customer/signup/", CustomerSignupView.as_view(), name="customersignup"),
    path("customer/login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("customer/logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("customer/reset-password/<email>/<token>/",
         CustomerResetPasswordView.as_view(), name="customerpr"),
    path("customer/forgot-password/",
         CustomerForgotPasswordView.as_view(), name="customerfp"),

    path("username-checker/", CustomerUsernameCheckerView.as_view(),
         name="usernamechecker"),

    
    #Operator signup/login
    path("operator/signup/",LogisticCompanySignupView.as_view(), name="logcompanysignup"),
    path("operator/login/", LogisticCompanyLoginView.as_view(), name="logcompanylogin"),
    path("operator/forgot-password/", LogisticCompanyForgotPasswordView.as_view(), name="logcompanyfp"),
    path("operator/reset-password/<email>/<token>/", LogisticCompanyResetPasswordView.as_view(), name="logcompanypr"),
    path("operator/logout/", LogoutView.as_view(), name='logout'),
    path("operator/accounts/detail/",
         OperatorAccountDetailView.as_view(), name='operatoraccount'),
         
    

]

templates/clienttemplates/clientbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Logistics Marketplace in Nepal</title>

     <script src="{% static 'logisticsstatic/plugins/jquery/js/jquery.min.js' %}"></script>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

      <!-- /site favicon -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <!-- Font Icon Styles -->
    <link rel="stylesheet" href="{% static 'logisticsstatic/assets/fonts/noir-pro/styles.css' %}">
    <link rel="stylesheet" href="{% static 'logisticsstatic/plugins/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'logisticsstatic/assets/vendor/gaxon-icon/styles.css' %}">
    <!-- /font icon Styles -->

    {% comment %} font awesome {% endcomment %}
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />

    <!-- Perfect Scrollbar stylesheet -->
    <link rel="stylesheet" href="{% static 'logisticsstatic/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}">
    <!-- /perfect scrollbar stylesheet -->

 
    <link rel="stylesheet" href="{% static 'logisticsstatic/assets/css/default/theme-semidark.min.css' %}">

    
     <style>
          body {
               font-family: 'Nunito', sans-serif;
          }

          .social-icons {
               font-size: 30px;
          }

          .title {
               color: rgb(28, 146, 101)
          }
     </style>
</head>

<body class="container-fluid">
     <div class="row" style="background-color: rgb(241, 240, 240); color: rgb(68, 68, 68)">
          <div class="col-md-6 mt-2">
               <h1 class="shippers-park"><a
                         style="text-decoration: none; color: rgb(37, 181, 121); font-weight: 600;"
                         href="">WWW.SHIPPERSPARK.COM</a>
               </h1>
               <h4 class="">A Logistics Marketplace in Nepal</h4>
          </div>
          <div class="col-md-6">
               <div class="row">
                    <div class="col-md-3 p-3 card text-center">
                         <h4>50+</h4>
                         <h6>Logistics</h6>
                    </div>
                    <div class="col-md-3 p-3 card text-center">
                         <h4>100+</h4>
                         <h6>Customers</h6>
                    </div>
                    <div class="col-md-3 p-3 card text-center">
                         <h4>5000+</h4>
                         <h6>Shipments/Day</h6>
                    </div>
                    <div class="col-md-3 p-3 card text-center">
                         <h4>2000+</h4>
                         <h6>Cities Covered</h6>
                    </div>
               </div>
          </div>
     </div>
     <div class="wrapper">
          {% block content %}

          {% endblock %}
     </div>
     <div class="row footer mt-3 p-3" style="background-color:rgb(241, 240, 240)">
          <div class="col-md-3">
               <h5 class="title">Logistics Marketplace in Nepal</h5>
               <hr>
               <img src="{% static 'assets/images/last-mile.jpg' %}" class="img-fluid" alt="">
               <div class="row">
                    <div class="col-md-12">
                         <p style="text-align: justify;">ShippersPark.Com is a Unified Digital Logistics Marketplace in
                              Nepal, that
                              connects every multi-branch logistics/transport companies with their individual/business
                              customers, partner
                              logistics companies, staffs and riders.</p>
                    </div>
               </div>
          </div>
          <div class="col-md-3">
               <h5 class="title">Quick Links</h5>
               <hr>
               <ul>
                    <li><a href="">Home</a></li>
                    <li><a href="">Contact us</a></li>
                    <li><a href="">Signup as a Customer</a></li>
                    <li><a href="">Signup as a Logistics Company</a></li>
                    <li><a href="">Become a Freelance Rider</a></li>
               </ul>
          </div>
          <div class="col-md-3">
               <h5 class="title">Using our platform</h5>
               <hr>
               <ul>
                    <li><a href="">Privacy Policy</a></li>
                    <li><a href="">Cookies Policy</a></li>
                    <li><a href="">Terms and Conditions</a></li>
                    <li><a href="">Logistics Company Terms</a></li>
                    <li><a href="">Customer Terms</a></li>
                    <li><a href="">Transportation Company Terms</a></li>
                    <li><a href="">Freelance Rider Terms</a></li>
               </ul>
          </div>
          <div class="col-md-3">
               <h5 class="title">Contacts and Support</h5>
               <hr>
               <div class="contact">
                    <p>Tutepani, Satdobato, Lalitpur<br>
                         contact@shipperspark.com</li>
                    <h6 class="font-weight-bold">Sales and Marketing Department</h6>
                    <li>marketing@shipperspark.com</li>
                    <li>9898989898/9898989898</li>
                    <h6 class="font-weight-bold">Support Department</h6>
                    <li>marketing@shipperspark.com</li>
                    <li>9898989898/9898989898</li>
                    <hr>
                    <div class="row">
                         <div class="col-md-2">
                              <a class="social-icons" href=""><i class="fab fa-facebook"></i></a>
                         </div>
                         <div class="col-md-2">
                              <a class="social-icons" href=""><i class="fab fa-instagram"></i></a>
                         </div>
                         <div class="col-md-2">
                              <a class="social-icons" href=""><i class="fab fa-whatsapp"></i></a>
                         </div>
                         <div class="col-md-2">
                              <a class="social-icons" href=""><i class="fab fa-viber"></i></a>
                         </div>
                         <div class="col-md-2">
                              <a class="social-icons" href=""><i class="fab fa-twitter"></i></a>
                         </div>
                         <div class="col-md-2">
                              <a class="social-icons" href=""><i class="fab fa-linkedin"></i></a>
                         </div>
                    </div>
               </div>
          </div>
     </div>




  
     <script src="{% static 'logisticsstatic/plugins/sweetalert2/js/sweetalert2.js' %}"></script>
     <script src="{% static 'assets/js/global/sweet-alert.js' %}"></script>
    

     {% if messages %}
     {% for message in messages %}
         {% if message.tags == 'success' %}
             <script>
                 let timerInterval;
                 swal({
                         type: "success",
                         title: "success",
                         text: "{{message}}"
                    });
             </script>
         {% elif message.tags == 'info' %}
             <script type=text/javascript>
                 let timerInterval;
                 swal({
                     type: "info",
                     title: "{{message}}",
                     text: "",
                     animation: true,
                     toast: true,
                     icon: 'info',
                     position: 'top-right',
                     showConfirmButton: false,
                     timer: 3000,
                     timerProgressBar: true,
                 });
             </script>
         {% elif message.tags == 'warning' %}
             <script type=text/javascript>
                 swal({
                     type: 'warning',
                     title: '{{message}}',
                     text: '!',
                     footer: '',
                     animation: true,
                     toast: true,
                     icon: 'warning',
                     position: 'top-right',
                     showConfirmButton: false,
                     timer: 3000,
                     timerProgressBar: true,
               });
             </script>
         {% elif message.tags == 'error' %}
             <script type=text/javascript>
                 swal({
                     type: 'error',
                     title: '{{message}}',
                     timer: 2000,
                     text: '',
                     footer: '',
                     animation: true,
                     toast: true,
                     icon: 'error',
                     position: 'top-right',
                     showConfirmButton: false,
                     timer: 3000,
                     timerProgressBar: true,
               });
             </script>
         {% endif %}
     {% endfor %}
 {% endif %}
<block js>

</block>
</body>
</html>

templates/clienttemplates/clientcomingsoon.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="shipperspark.com is a unified logistics marketplace in nepal where all types of multi-branch logistics/courier/transport companies, their staffs, riders can join together to handle the shipments process of individuals and regular customers like ecommerce, banks etc.">
    <meta name="author" content="Sarobar Technology Pvt. Ltd.">
    <title>shipperspark.com</title>
    <style>
        html {
      box-sizing: border-box;
      height: 100%;
    }
    *, *:before, *:after {
      box-sizing: inherit;
    }
    body {
      height: 100%;
      margin: 0;
    }
    .video-wrapper {
      width:100%;
      height:100vh;
      overflow: hidden;
      
    }
    </style>
</head>
<body style="margin:0px;padding:0px;overflow:hidden">
    <iframe src="https://www.youtube.com/embed/4mU2ixUPdDM?autoplay=1&mute=1&loop=1&controls=0" controls=0 frameborder="0" style="overflow:hidden;overflow-x:hidden;overflow-y:hidden;height:100%;width:100%;position:absolute;" height="100%" width="100%"></iframe>
</body>
<script>
  setTimeout(function(){
    location.reload()
  }, 35000);
</script>
</html>

templates/clienttemplates/clientcontact.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Display map navigation controls</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
<link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js"></script>
<style>
body { margin: 0; padding: 0; }
#map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
</head>
<body>
<div id="map"></div>
<script>
	mapboxgl.accessToken = 'pk.eyJ1Ijoic2VlbWEtcmFpIiwiYSI6ImNrbTBodGNmMDAwMnkycG1zZW9iOGs3OXUifQ.Lrz7tWV9dV5Mao7D4akG9w';
    var map = new mapboxgl.Map({
        container: 'map', // container id
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [-74.5, 40], // starting position
        zoom: 9 // starting zoom
    });

    // Add zoom and rotation controls to the map.
    map.addControl(new mapboxgl.NavigationControl());
</script>

</body>
</html>

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block css %}

<style>
    .shippers-park {
        font-weight: bold;
    }

    @media only screen and (max-width: 600px) {
        .shippers-park {
            font-size: 20px !important;
        }
    }
</style>
{% endblock %}


{% block content %}
<div class="main-page">
    <div class="row mt-3">
        <div class="col-md-12 mt-2">
            <h4 style="text-align:center;">About Us</h4>
            <p class="text-center">ShippersPark.Com is a Unified Digital Logistics Marketplace in Nepal, that connects
                every multi-branch logistics/transport companies with their individual/business customers, partner
                logistics companies, staffs and riders. If you are a logistics service provider, you can work with
                multiple logistics companies to deliver your customers parcel everywhere. If you need delivery service,
                you can find a lots of logistics companies ready to provide you the logistics services. </p>
        </div>
    </div>


    <div class="row mt-3">
        <div class="col-md-6">
            <div class="card p-3">

                <div class="row">
                    <div class="col-md-8">
                        <h3 class="float-left" style="color:rgb(28, 179, 121);">Are you a Logistcs Company?</h3>
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'umapp:logcompanylogin' %}" class="float-right">Login</a>
                    </div>
                </div>
                <hr>
                <div class="p-3">
                    <h5>Benefits of Using our system</h5>
                    <ul>
                        <li>Complete shipment-flow record in one system</li>
                        <li>Separate Panel for all your branches</li>
                        <li>Branch wise Admin, Staffs and Delivery Person</li>
                        <li>Real time shipment status update</li>
                        <li>Working with other logistics partners is easy and standard</li>
                        <li>Delivery Person App</li>
                        <li>Great Exposure to customers</li>
                        <li>24/7 Support from us</li>
                    </ul>
                    <a href="{% url 'umapp:logcompanysignup' %}" class="btn btn-outline-success">Become a Logistics
                        Partner</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card p-3">

                <div class="row">
                    <div class="col-md-8">
                        <h3 class="float-left" style="color:rgb(28, 179, 121);">Need Logistics Services?</h3>
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'umapp:customerlogin' %}" class="float-right">Login</a>
                    </div>
                </div>
                <hr>
                <div class="p-3">
                    <h5>Benefits of Using our system</h5>
                    <ul>
                        <li>Send your parcel anywhere</li>
                        <li>Take orders from everywhere and grow your custmers and sales</li>
                        <li>Work with multiple logistics companies at once</li>
                        <li>Choose the best logistics company for different locations</li>
                        <li>Get Real time shipment status update</li>
                        <li>Integrate it to your online system</li>
                        <li>24/7 Support from us</li>
                    </ul>
                    <a href="{% url 'umapp:customersignup' %}" class="btn btn-outline-success">Meet your Logistics
                        service
                        Providers</a>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}