lmsproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from lcapiapp.views import *

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("umapp.urls")),
    path('', include("lmsapp.urls")),

    path('api/v1/customer/', include("lcapiapp.urls")),
    path('api/v1/logistics/', include("lbapiapp.urls")),

    # path('password-reset/check/token/<uidb64>/<token>/',
    #      PasswordTokenCheckAPI.as_view(), name='token-check'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

umapp/urls.py
from django.urls import path, include
from .views import *

app_name = "umapp"
urlpatterns = [
    
#     path("operator/reset-password/",
#          LogisticsAdminResetPasswordView.as_view(), name="laresetpassword"),
    # path("operator/login/", LogisticsAdminLoginView.as_view(),
    #      name="logisticsadminlogin"),
    


    # Country
    path('operator/country/create',
         CountryCreateView.as_view(), name='countrycreate'),
    path('operator/country/<int:pk>/edit/',
         CountryUpdateView.as_view(), name='countryedit'),


    # province
    # path('operator/province/list/', ProvinceView.as_view(), name='provincelist'),
    path('operator/province/create/',
         ProvinceCreateView.as_view(), name='provincecreate'),
    path('operator/province/<int:pk>/edit/',
         ProvinceUpdateView.as_view(), name='provinceedit'),
    path('operator/province/delete/<int:pk>/',
         ProvinceDelete.as_view(), name='provincedelete'),


    # #District url
    # path('operator/district/list/', DistrictView.as_view(), name="districtlist"),
    path('operator/district/create/',
         DistrictCreateView.as_view(), name="districtcreate"),
    path('operator/district/update/<int:pk>/',
         DistrictUpdate.as_view(), name="districtedit"),


    # #City Url
    # path('operator/cities/list/',CityView.as_view(), name='citylist'),
    path('operator/cities/create/', CityCreateView.as_view(), name='citycreate'),
    path('operator/city/update/<int:pk>/',
         CityUpdateView.as_view(), name="cityedit"),

     path("initial-setup/", InitialSetupView.as_view(), name="initialsetup"),


    # branchoperator
    path('operator/branch-operator/list',
         BranchOperatorListView.as_view(), name='operatorlist'),
    path('operator/branch-operator/create',
         BranchOperatorCreateView.as_view(), name='operatorcreate'),
    path('operator/branch-operator/update/<int:pk>',
         BranchOperatorUpdateView.as_view(), name='operatorupdate'),


    # Branch operator password change
    path('operator/branch-operator/pass/change/<int:pk>/',
         BranchOperatorPasswordChangeView.as_view(), name='operatorpasschange'),



    # Shipping Zone
    path('operator/branch-operator/shipping/zone/',
         LogisticBranchShippingListZoneView.as_view(), name='shippinglist'),
    path('operator/branch-operator/shipping/zone/create',
         LogisticBranchShippingZoneCreateView.as_view(), name='shippingzonecreate'),
    path('operator/branch-operator/shipping/zone/update/<int:pk>/',
         LogisticBranchShippingZoneUpdateView.as_view(), name='shippingupdate'),
    path('operator/branch-operator/shipping/zone/detail/<int:pk>/',
         logisticsBranchShippingZoneDetailView.as_view(), name='shippingdetail'),
     path('operator/ajax/serch/city/', AjaxCitySearchView.as_view(), name = 'ajaxcitysearach'),
     # path('operator/ajax/list/city/', AjaxCitySearchListView.as_view(), name = 'ajaxcitysearchlist'),


    # DeliveryType/

    path('operator/branch-operator/create/deliverytype/',
         DeliveryTypeView.as_view(), name='deliverytype'),
    path('operator/branch-operator/update/deliverytype/<int:pk>/',
         DeliveryTypeUpdateView.as_view(), name='deliverytypeupdate'),

     #settings
    path('operator/branch-operator/settings/',
         SettingView.as_view(), name='settings'),
     path('operator/branch-operator/settings/ajax/search/city/', AjaxSettingsCitySearchView.as_view(), name = 'ajaxsettingscitysearch'),
     # path('operator/branch-operator/settings/ajax/search/district/', AjaxSettingsDistrictSearchView.as_view(), name = 'ajaxsettingsdistrictsearch'),
     # path('operator/branch-operator/settings/ajax/search/province/', AjaxSettingsProvinceSearchView.as_view(), name = 'ajaxsettingsprovincesearch'),
     # path('operator/branch-operator/settings/ajax/search/country/', AjaxSettingsCountrySearchView.as_view(), name = 'ajaxsettingscountrysearch'),
     


    # ajax
    path('operator/branch-operator/email/validate/',
         validateoperatoremailview, name='checkemail'),

    path('countryname/check/', CountryAjaxCheck, name='checkcountryname'),
    path('provincename/check/', ProvinceAjaxCheck, name='checkprovincename'),
    path('districtname/check/', DistrictAjaxCheck, name='checkdistrictname'),
    path('cityname/check/', CityAjaxCheck, name='checkcityname'),

    # operator customer
    path('operator/customers/list/',
         OperatorCustomersListView.as_view(), name='opcustomerslist'),
    path('operator/customers/create/',
         OperatorCustomersCreateView.as_view(), name='opcustomerscreate'),
    path('operator/customers/update/<int:pk>/',
         OperatorCustomersUpdateView.as_view(), name='opcustomersupdate'),
    path('operator/customers/change-password/<int:pk>',
         OperatorCustomersPasswordChangeView.as_view(), name='opcustomerspc'),
    path('operator/customers/detail/<int:pk>/',
         OperatorCustomersDetailView.as_view(), name='opcustomersdetail'),
    path('operator/customers/payment-list/',
         LogisticAdminLogisticsCustomerPaymentListView.as_view(), name="lalcpaymentlist"),


     # operator rider
     path('operator/deliveryperson/list/',
         OperatorDeliveryPersonListView.as_view(), name='opdeliverypersonlist'),
     path('operator/deliveryperson/create/',
         OperatorDeliveryPersonCreateView.as_view(), name='opdeliverypersoncreate'),
     path('operator/deliveryperson/detail/<int:pk>/',
         OperatorDeliveryPersonDetailView.as_view(), name='opdeliverypersondetail'),
     path('operator/deliveryperson/update/<int:pk>/',
         OperatorDeliveryPersonUpdateView.as_view(), name='opdeliverypersonupdate'),
     path('operator/deliveryperson/change-password/<int:pk>',
         OperatorDeliveryPersonPasswordChangeView.as_view(), name='opdeliverypersonpc'),
     



    #Customer signup/login
    path("customer/signup/", CustomerSignupView.as_view(), name="customersignup"),
    path("customer/login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("customer/logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("customer/reset-password/<email>/<token>/",
         CustomerResetPasswordView.as_view(), name="customerpr"),
    path("customer/forgot-password/",
         CustomerForgotPasswordView.as_view(), name="customerfp"),

    path("username-checker/", CustomerUsernameCheckerView.as_view(),
         name="usernamechecker"),

    
    #Operator signup/login
    path("operator/signup/",LogisticCompanySignupView.as_view(), name="logcompanysignup"),
    path("operator/login/", LogisticCompanyLoginView.as_view(), name="logcompanylogin"),
    path("operator/forgot-password/", LogisticCompanyForgotPasswordView.as_view(), name="logcompanyfp"),
    path("operator/reset-password/<email>/<token>/", LogisticCompanyResetPasswordView.as_view(), name="logcompanypr"),
    path("operator/logout/", LogoutView.as_view(), name='logout'),
    path("operator/accounts/detail/",
         OperatorAccountDetailView.as_view(), name='operatoraccount'),
         
    

]

templates/logisticstemplates/logcompanyforgotpassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

<head>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <!-- /meta tags -->
    <title>Login - Logistics Company</title>

    <!-- Site favicon -->
    <link rel="shortcut icon" href="{% static 'logisticsstatic/favicon.png' %}" type="image/x-icon">
    <!-- /site favicon -->

    <!-- Font Icon Styles -->
    <link rel="stylesheet" href="{% static 'logisticsstatic/assets/fonts/noir-pro/styles.css' %}">
    <link rel="stylesheet" href="{% static 'logisticsstatic/plugins/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'logisticsstatic/assets/vendor/gaxon-icon/styles.css' %}">
    <!-- /font icon Styles -->

    <!-- Perfect Scrollbar stylesheet -->
    <link rel="stylesheet" href="{% static 'logisticsstatic/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}">
    <!-- /perfect scrollbar stylesheet -->

    <link rel="stylesheet" type="text/css"
        href="{% static 'logisticsstatic/plugins/owl.carousel/css/owl.carousel.min.css' %}" media="all" />
    <link rel="stylesheet" type="text/css" href="{% static 'logisticsstatic/plugins/chartist/css/chartist.min.css' %}"
        media="all" />

    <link rel="stylesheet" href="{% static 'logisticsstatic/assets/css/default/theme-semidark.min.css' %}">

    <script>
        var rtlEnable = '';
        var $mediaUrl = 'https://drift-admin.g-axon.work/';
        var $baseUrl = 'https://drift-admin.g-axon.work/';
        var current_path = window.location.href.split('https://drift-admin.g-axon.work/').pop();
       
    </script>

    <script src="{% static 'logisticsstatic/plugins/jquery/js/jquery.min.js' %}"></script>
    <script src="{% static 'logisticsstatic/plugins/moment/js/moment.min.js' %}"></script>
    <script src="{% static 'logisticsstatic/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Perfect Scrollbar jQuery -->
    <script src="{% static 'logisticsstatic/plugins/perfect-scrollbar/js/perfect-scrollbar.min.js' %}"></script>
    <!-- /perfect scrollbar jQuery -->

</head>

<body class="dt-layout--default dt-sidebar--fixed dt-header--fixed">
    <!-- Loader -->
    <div class="dt-loader-container">
        <div class="dt-loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10">
                </circle>
            </svg>
        </div>
    </div>
    <!-- /loader -->
    <div class="dt-root">
        <div class="dt-root__inner">
            <div class="dt-login--container">
    
                <!-- Login Content -->
                <div class="dt-login__content-wrapper">
    
                    <!-- Login Background Section -->
                    <div class="dt-login__bg-section">
    
                        <div class="dt-login__bg-content">
                            <!-- Login Title -->
                            <h1 class="dt-login__title">Reset Your Password</h1>
                            <!-- /login title -->
                            {% if error %}
                            <p class="f-16">Error Attempt During Reset Password</p>
                            <span style="color: rgb(208, 130, 130);">{{error}}</span>
                            {% else %}
                            <p class="f-16">Welcome user, please provide your email to reset your password. </p>
                            {% endif %}
                        </div>
        
                        <!-- Brand logo -->
                        <div class="dt-login__logo">
                            <a class="dt-brand__logo-link" href="{% url 'lmsapp:clienthome' %}">
                                <img class="dt-brand__logo-img" src="{% static 'logisticsstatic/favicon.png' %}" style="height: 60px; object-fit: contain;" alt="Organization">
                            </a>
                        </div>
                        <!-- /brand logo -->
    
                    </div>
                    <!-- /login background section -->
    
                    <!-- Login Content Section -->
                    <div class="dt-login__content">
    
                        <!-- Login Content Inner -->
                        <div class="dt-login__content-inner">
    
                            <!-- Form -->
                            <form method="POST">
                                {% if request.GET.m == 's' %}
                                <div class="col-md-12">
                                    <p style="font-size: 25px;">Reset Link has been sent.<br> Please Check Your Email Immediatly</p>
                                </div>
                                {% else %}
                                
                                {% csrf_token %}
                                <!-- Form Group -->
                                <div class="form-group search-box right-side-icon mw-100">
                                    <label class="sr-only" for="email-1">Email address</label>
                                    {{form.email}}
                                    <br>
                                    <span style="color: rgb(208, 130, 130);">{{form.email.errors}}</span>
                                    <span class="search-icon"><i class="icon icon-mail icon-lg"></i></span>
                                </div>
                                <!-- /form group -->

                                <p class="mb-8">Don't remember your email? &nbsp;
                                    <a class="small" href="#">Contact Support.</a>
                                </p>

                                <!-- Form Group -->
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary text-uppercase">Get Link</button>
                                </div>
                                <!-- /form group -->
                                {% endif %}
                            </form>
                            <!-- /form -->
    
                        </div>
                        <!-- /login content inner -->
    
                        <!-- Login Content Footer -->
                        
                        <!-- /login content footer -->
    
                    </div>
                    <!-- /login content section -->
    
                </div>
                <!-- /login content -->
    
            </div>
        </div>
    </div>
    <!-- masonry script -->
    <script src="{% static 'logisticsstatic/plugins/masonry-layout/js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'logisticsstatic/plugins/sweetalert2/js/sweetalert2.js' %}"></script>
    <script src="{% static 'logisticsstatic/assets/js/default/functions.js' %}"></script>
    <script src="{% static 'logisticsstatic/assets/js/default/customizer.js' %}"></script>

    <script src="{% static 'logisticsstatic/assets/js/default/script.js' %}"></script>
    {% block js %}
    {% endblock %}
</body>

</html>

templates/logisticstemplates/opcustomerscreate.html
<div class="modal-header">
	<h5 class="modal-title" id="mySmallModalLabel">{{page}} Customer</h5>
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<form method="POST" action="{% url 'umapp:opcustomerscreate' %}" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="modal-body">
    <div class="row" style="margin:10px;">
          <!-- <label for="">Title *</label>
          {{form.as_p}}

          <label for="" style='padding-top:20px;'>Image <small>(This field is optional)</small></label>
        {{deliveryform.image}} -->
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Email *</label>
                    {{form.email}}
                    <span id="errorp" style="padding: 0; margin: 0; "></span> 
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Password *</label>
                    {{form.password}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Full Name </label>
                    {{form.full_name}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Contact Number</label>
                    {{form.contact_number}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Company Name</label>
                    {{form.company_name}}
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="">City</label>
                    {{form.city}}
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Address</label>
                    {{form.address}}
                </div>
            </div>
       
            


	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-warning text-left" data-dismiss="modal">Close</button>
		<button class="btn btn-primary text-left">Save</button>
	</div>
</form>

templates/logisticstemplates/opcustomerslist.html
{% extends 'logisticstemplates/logisticsadminbase.html' %}
{% load static %}
{% block title %}Customer Information{% endblock %}


{% block content %}
<div class="dt-content-wrapper">
    <div class="dt-content">
      <!-- <div class="dt-page__header">
        <h1 class="dt-page__title">Customer Information</h1>
      </div> -->
      <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header card-nav border-bottom-0">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h3 class="dt-card__title" id="status-title">Customer Informations</h3>
                         <a data-toggle="modal" data-target="#create-modal" data-remote="{% url 'umapp:opcustomerscreate' %}" class="d-inline-block" style="color:#512DA8;cursor: pointer;"><i class="icon icon-circle-add-o mr-2"></i>Create Customer</a> 

                    </div>

                </div>

                <!-- <div class="dt-card"> -->
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>S.N</th>
                                <th>Company Name</th>
                                <th>Phone Number</th>
                                <th>Address</th>
                                <th>Action</th>


                            </tr>
                        </thead>
                        
                        <tbody>
                            {% for basic in clist %}
                            <tr>
                                <td><a>{{forloop.counter|truncatechars:20}}</a></td>
                                <td ><a href="{%url 'umapp:opcustomersdetail' basic.pk %}">{{basic.company_name|truncatechars:20}}</a></td>
                                <td><a>{{basic.contact_number|truncatechars:20}}</a></td>
                                <td><a>{{basic.address|truncatechars:20}}</a></td>

                                <td>
                                <a data-toggle="modal" data-target="#update-modal" data-remote="{% url 'umapp:opcustomersupdate' basic.id %}" class="btn-sm btn-light " title="Update"><i class="fas fa-pencil"></i></a>

                                <a data-toggle="modal" data-target="#reset-modal" data-remote="{% url 'umapp:opcustomerspc' basic.user.id %}"class="btn-sm btn-light" title="Change Password"><i class="fas fa-key"></i></a>

                                <a style="cursor:default;" href="{% url 'umapp:opcustomersdetail' basic.pk %}"class="btn-sm btn-light" title="View Customer Detail"><i class="fas fa-angle-double-right"></i></a>
                                

                                </td> 
                                


                            </tr>
                            {% endfor %}

                        </tbody>

                    </table>


 {% if is_paginated %}
  <ul class="pagination justify-content-center ">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>

                    <!-- <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">&laquo; first</a>
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                    
                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                    
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div> -->




                
                <!-- </div> -->


                

            </div>


        </div>


      </div>




    </div>
</div>
      




{% endblock %}

templates/logisticstemplates/opcustomersupdate.html
<div class="modal-header">
	<h5 class="modal-title" id="mySmallModalLabel">Update Customer</h5>
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<form method="POST" action="{% url 'umapp:opcustomersupdate' object.id %}" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="modal-body">
    <div class="row" style="margin:10px;">
          <!-- <label for="">Title *</label>
          {{form.as_p}}

          <label for="" style='padding-top:20px;'>Image <small>(This field is optional)</small></label>
        {{deliveryform.image}} -->
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Full Name </label>
                    {{form.full_name}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Contact Number</label>
                    {{form.contact_number}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Company Name</label>
                    {{form.company_name}}
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="">City</label>
                    {{form.city}}
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Address</label>
                    {{form.address}}
                </div>
            </div>
       
            


	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-warning text-left" data-dismiss="modal">Close</button>
		<button class="btn btn-primary text-left">Save</button>
	</div>
</form>

templates/logisticstemplates/opdeliverypersoncreate.html
<div class="modal-header">
	<h5 class="modal-title" id="mySmallModalLabel">{{page}} Rider</h5>
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<form method="POST" action="{% url 'umapp:opdeliverypersoncreate' %}" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="modal-body">
    <div class="row" style="margin:10px;">
          <!-- <label for="">Title *</label>
          {{form.as_p}}

          <label for="" style='padding-top:20px;'>Image <small>(This field is optional)</small></label>
        {{deliveryform.image}} -->
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Email *</label>
                    {{form.email}}
                    <span id="errorp" style="padding: 0; margin: 0; "></span> 
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Password *</label>
                    {{form.password}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Full Name </label>
                    {{form.full_name}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Image</label>
                    {{form.image}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Contact Number</label>
                    {{form.mobile}}
                </div>
            </div>
           

            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Address</label>
                    {{form.address_city}}
                </div>
            </div>

            
       
            


	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-warning text-left" data-dismiss="modal">Close</button>
		<button class="btn btn-primary text-left">Save</button>
	</div>
</form>