lmsapp/urls.py
from django.urls import path
from .views import *
from . import views


app_name = "lmsapp"
urlpatterns = [

    # 1 System Operator Views


    # 2 Logistics Operator Views
    path("operator/dashboard/", LogisticsAdminHomeView.as_view(), name="lahome"),
    path("operator/shipments/list/",
         LogisticsAdminShipmentListView.as_view(), name="lashipmentlist"),
    path("operator/shipments/new-create/",
         LogisticsAdminShipmentCreateView.as_view(), name="lashipmentcreate"),
    path("operator/shipments/update-<int:pk>/",
         LogisticsAdminShipmentUpdateView.as_view(), name="lashipmentupdate"),
    path("operator/shipments/detail-<int:pk>/",
         LogisticsAdminShipmentDetailView.as_view(), name="lashipmentdetail"),

    path("operator/bundles/list/",
         LogisticsAdminBundleListView.as_view(), name="labundlelist"),
    path("operator/bundle/update-<int:pk>/",
         LogisticsAdminBundleUpdateView.as_view(), name="labundleupdate"),
    path("operator/bundles/incoming-list/",
         LogisticsAdminIncomingBundleListView.as_view(), name="laincomingbundlelist"),

    path("operator/bundles/cmp/laloadbundlelist/",
         CmpLogisticsAdminLoadBundleListView.as_view(), name="cmplaloadbundlelist"),
    path("operator/bundles/cmp/labundleinfo-<int:pk>/",
         CmpLogisitcsAdminLoadBundleInfoView.as_view(), name="cmplabundleinfo"),
    path("operator/bundles/cmp/laloadincomingbundlelist/",
         CmpLogisticsAdminLoadIncomingBundleListView.as_view(), name="cmplaloadincomingbundlelist"),

    path("operator/bundles/ajax/labundlechangestatus/",
         AjaxLogisticsAdminBundleChangeStatusView.as_view(), name="ajaxlabundlechangestatus"),
    path("operator/shipments-bundle/ajax/shipment-charge/<attribute>/update/",
         AjaxLogisticsAdminShipmentBundleShipmentChargeUpdateView.as_view(), name="ajaxlashipmentbundleshipmentchargeupdate"),
    path("operator/shipments/ajax/labundlechangestatus/",
         AjaxLogisticsAdminBundleShipmentChangeStatusView.as_view(), name="ajaxlabundleshipmentchangestatus"),
    # shipment bundle create modal
    path("operator/shipment-bundle/ajax/destination-option-modal/",
         AjaxLogisticsAdminShipmentBundleDestinationOptionModalView.as_view(), name="ajaxlashipmentbundledestinationoptionmodal"),

    path("operator/shipments/cmp/laloadshipmentlist/",
         CmpLogisticsAdminLoadShipmentListView.as_view(), name="cmplaloadshipmentlist"),
    path("operator/shipments/cmp/lashipmentinfo-<int:pk>/",
         CmpLogisitcsAdminLoadShipmentInfoView.as_view(), name="cmplashipmentinfo"),
    path("operator/shipments/cmp/laloadenquirylist/",
         CmpLogisticsAdminLoadEnquiryListView.as_view(), name="cmplaloadenquirylist"),

    path("operator/shipments/ajax/lashipmentactivity-<int:pk>/",
         AjaxLogisticsAdminShipmentActivityCreateView.as_view(), name="ajaxlashipmentactivitycreate"),
    path("operator/shipments/ajax/lashipmentchangestatus/",
         AjaxLogisticsAdminShipmentChangeStatusView.as_view(), name="ajaxlashipmentchangestatus"),
    path("operator/shipments/ajax/shipment-charge/<attribute>/update/",
         AjaxLogisticsAdminShipmentChargeUpdateView.as_view(), name="ajaxlashipmentchargeupdate"),

    path("operator/shipment/shipping-label/<int:pk>/",
         LogisticAdminShipmentShippingLabelView.as_view(), name="lashipmentshippinglabel"),
    # path("operator/shipment/bulk-shipping-label/",
    #      LogisticAdminShipmentBulkShippingLabelView.as_view(), name-"lashipmentbulkshipmentlabel"),
    path("operator/shipment/bulk-shipping-label/",
         LogisticAdminShipmentShippingLabelView.as_view(), name="lashipmentbulkshipmentlabel"),

    path("settings/", LogisticsAdminSettingsView.as_view(), name="lasettings"),

    path('operator/branch-operator/customer/ticket/list/',
         CustomerSupportTicketListView.as_view(), name='operatorcustomerticketlist'),

    path('operator/branch-operator/customer/ticket/detail/<int:pk>/',
         CustomerSupportTicketDetailView.as_view(), name='operatorcustomerticketdetail'),

    path('operator/branch-operator/customer/ticket/update/<int:pk>/',
         CustomerSupportTicketUpdateView.as_view(), name='operatorcustomerticketupdate'),

    path('operator/branch-operator/customer/ticket/support/ajax/<int:pk>/',
         CustomerSupportTicketAjaxView.as_view(), name='ticketraiseajax'),

    path('operator/branch-operator/customer/ticket/status/list/',
         CustomerTicketNoticeStatusList.as_view(), name='ticketstatuslist'),
    path('operator/branch-operator/customer/message/status/list/',
         CustomerTicketFollowUpdMessageStatusList.as_view(), name='messagestatuslist'),
    # path('operator/branch-operator/customer/ticket/support/ajax/list/', CustomerSupportTicketListAjaxView.as_view(), name='operatorcustomerticketajaxlist'),

    path('operator/branch-operator/customer/notice/list/',
         LogisticsNoticeListView.as_view(), name='opnoticelist'),
    path('operator/branch-operator/customer/notice/create/',
         LogisticsNoticeCreateView.as_view(), name='opnoticecreate'),
    path('operator/branch-operator/customer/notice/update/<int:pk>/',
         LogisticsNoticeUpdateView.as_view(), name='opnoticeupdate'),
    path('operator/branch-operator/customer/notice/detail/<int:pk>/',
         LogisticsNoticeDetailView.as_view(), name='opnoticedetail'),

    path('operator/logistic-customer/ajax/list/',
         AjaxLALogisticCustomerListView.as_view(), name="ajaxlalogisticcustomerlist"),

    path('operator/logistic-customer/<int:pk>/shipments-list/payment/',
         LogisticsAdminLogisticsCustomerShipmentPaymentListView.as_view(), name="lalcshipmentpaymentlist"),
    

    path('operator/logistic-customer/quotation/request/list/',
         LogisticsCustomerRequestQuotationFromBranch.as_view(), name="customerrequestquotation"),
    path('operator/logistic-customer/quotation/request/approved/list/',
         LogisticsCustomerRequestQuotationFromBranchApproved.as_view(), name="customerrequestquotationapproved"),
    path('operator/logistic-customer/signed/quotation/request/approved/list/',
         LogisticsCustomerSignedRequestQuotationFromBranchApproved.as_view(), name="customerrequestsignedquotationapproved"),
    path('operator/logistic-customer/quotation/request/create/<int:pk>/',
         LogisticsCustomerRequestQuotationFromBranchCreateView.as_view(), name="customerrequestquotationcreate"),
    path('operator/logistic-customer/quotation/request/update/<int:pk>/',
         LogisticsCustomerRequestQuotationFromBranchUpdateView.as_view(), name="customerrequestquotationupdate"),
    path('operator/logistic-customer/quotation/request/detail/<int:pk>/',
         LogisticsCustomerRequestQuotationFromBranchDetail.as_view(), name="customerrequestquotationdetail"),

    path('operator/logistic-customer/quotation/request/ajax/',
         LogisticsCustomerRequestQuotationFromBranchApprovedAjaxView.as_view(), name="customerrequestquotationajax"),
    path('operator/logistic-customer/quotation/request/ajax2/',
         LogisticsCustomerRequestQuotationFromBranchApprovedAjaxView2.as_view(), name="customerrequestquotationajax2"),

    # Customer Payment
    path('operator/payment/lc-<int:pk>-payment/',
         LogisticAdminLogisticsCustomerShipmentPaymentView.as_view(), name="lalcshipmentpayment"),
    path('operator/logistic-customer/shipment-process-payment/',
         LogisticsAdminLogisticsCustomerShipmentProcessPaymentView.as_view(), name="lalcshipmentprocesspayment"),
    path('operator/customer-payment/list/',
         OperatorCustomerPaymentListView.as_view(), name="opcustomerpaymentlist"),
    path('operator/customer-payment/detail/<int:pk>/',
         OperatorCustomerPaymentDetailView.as_view(), name="opcustomerpaymentdetail"),
    path('operator/logistic-customer/shipment-process-payment/print/',
         LogisticAdminLogisticsCustomerShipmentProcessPaymentPrintView.as_view(), name="lalcshipmentprocesspaymentprint"),
    path('operator/logistic-customer/shipment-process-payment/download/',           
         LogisticAdminLogisticsCustomerShipmentProcessPaymentDownloadView.as_view(), name="lalcshipmentprocesspaymentdownload"),

    # logistics admin sidebar
    path("operator/cmp/sidebardetail/",
         CmpLogisticsAdminLoadSidebarView.as_view(), name="cmplasidebardetail"),


    # --------------------------------------------
    # Logistics customer panel urls
    # 3 Logistic Customers Views

    path("customer/dashboard/",
         LogisticsCustomerDashboardView.as_view(), name="lcdashboard"),
     path("customer/profile/", LogisticCustomerProfileView.as_view(), name="customerprofileview"),
     path("customer/profile/update/<int:pk>/", LogisticCustomerProfileUpdateView.as_view(), name="customerprofilupdate"),

    # shipment management
    path('customer/shipment-list/', CustomerShipmentListView.as_view(),
         name='customershipmentlist'),
    path('customer/shipment-<int:pk>-detail/',
         CustomerShipmentDetailView.as_view(), name='customershipmentdetail'),
    path('customer/request-shipment/',
         CustomerShipmentCreateView.as_view(), name='customershipmentcreate'),
    path('customer/get-filtered-branches/',
         CustomerGetFilteredLogisticsView.as_view(), name='getfilteredlogistics'),
    path('customer/logsitic-company/cost/',
         CustomerLogisticsBranchCost.as_view(), name='branchcost'),


    path('customer/bulk-shipment/upload/',
         CustomerBulkShipmentUpload.as_view(), name='customerbulkshipmentupload'),

    # tickets
    path('customer/support/ticket/list/',
         CustomerSupportTicketRaiseListView.as_view(), name='customerticketlist'),
    path('customer/support/ticket/create/',
         CustomerSupportTicketCreateView.as_view(), name='customerticketcreate'),
    path('customer/support/ticket/detail/<int:pk>/',
         CustomerSupportTicketDetail.as_view(), name='customerticketdetail'),

lmsproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from lcapiapp.views import *

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("umapp.urls")),
    path('', include("lmsapp.urls")),

    path('api/v1/customer/', include("lcapiapp.urls")),
    path('api/v1/logistics/', include("lbapiapp.urls")),

    # path('password-reset/check/token/<uidb64>/<token>/',
    #      PasswordTokenCheckAPI.as_view(), name='token-check'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

umapp/urls.py
from django.urls import path, include
from .views import *

app_name = "umapp"
urlpatterns = [
    
#     path("operator/reset-password/",
#          LogisticsAdminResetPasswordView.as_view(), name="laresetpassword"),
    # path("operator/login/", LogisticsAdminLoginView.as_view(),
    #      name="logisticsadminlogin"),
    


    # Country
    path('operator/country/create',
         CountryCreateView.as_view(), name='countrycreate'),
    path('operator/country/<int:pk>/edit/',
         CountryUpdateView.as_view(), name='countryedit'),


    # province
    # path('operator/province/list/', ProvinceView.as_view(), name='provincelist'),
    path('operator/province/create/',
         ProvinceCreateView.as_view(), name='provincecreate'),
    path('operator/province/<int:pk>/edit/',
         ProvinceUpdateView.as_view(), name='provinceedit'),
    path('operator/province/delete/<int:pk>/',
         ProvinceDelete.as_view(), name='provincedelete'),


    # #District url
    # path('operator/district/list/', DistrictView.as_view(), name="districtlist"),
    path('operator/district/create/',
         DistrictCreateView.as_view(), name="districtcreate"),
    path('operator/district/update/<int:pk>/',
         DistrictUpdate.as_view(), name="districtedit"),


    # #City Url
    # path('operator/cities/list/',CityView.as_view(), name='citylist'),
    path('operator/cities/create/', CityCreateView.as_view(), name='citycreate'),
    path('operator/city/update/<int:pk>/',
         CityUpdateView.as_view(), name="cityedit"),

     path("initial-setup/", InitialSetupView.as_view(), name="initialsetup"),


    # branchoperator
    path('operator/branch-operator/list',
         BranchOperatorListView.as_view(), name='operatorlist'),
    path('operator/branch-operator/create',
         BranchOperatorCreateView.as_view(), name='operatorcreate'),
    path('operator/branch-operator/update/<int:pk>',
         BranchOperatorUpdateView.as_view(), name='operatorupdate'),


    # Branch operator password change
    path('operator/branch-operator/pass/change/<int:pk>/',
         BranchOperatorPasswordChangeView.as_view(), name='operatorpasschange'),



    # Shipping Zone
    path('operator/branch-operator/shipping/zone/',
         LogisticBranchShippingListZoneView.as_view(), name='shippinglist'),
    path('operator/branch-operator/shipping/zone/create',
         LogisticBranchShippingZoneCreateView.as_view(), name='shippingzonecreate'),
    path('operator/branch-operator/shipping/zone/update/<int:pk>/',
         LogisticBranchShippingZoneUpdateView.as_view(), name='shippingupdate'),
    path('operator/branch-operator/shipping/zone/detail/<int:pk>/',
         logisticsBranchShippingZoneDetailView.as_view(), name='shippingdetail'),
     path('operator/ajax/serch/city/', AjaxCitySearchView.as_view(), name = 'ajaxcitysearach'),
     # path('operator/ajax/list/city/', AjaxCitySearchListView.as_view(), name = 'ajaxcitysearchlist'),


    # DeliveryType/

    path('operator/branch-operator/create/deliverytype/',
         DeliveryTypeView.as_view(), name='deliverytype'),
    path('operator/branch-operator/update/deliverytype/<int:pk>/',
         DeliveryTypeUpdateView.as_view(), name='deliverytypeupdate'),

     #settings
    path('operator/branch-operator/settings/',
         SettingView.as_view(), name='settings'),
     path('operator/branch-operator/settings/ajax/search/city/', AjaxSettingsCitySearchView.as_view(), name = 'ajaxsettingscitysearch'),
     # path('operator/branch-operator/settings/ajax/search/district/', AjaxSettingsDistrictSearchView.as_view(), name = 'ajaxsettingsdistrictsearch'),
     # path('operator/branch-operator/settings/ajax/search/province/', AjaxSettingsProvinceSearchView.as_view(), name = 'ajaxsettingsprovincesearch'),
     # path('operator/branch-operator/settings/ajax/search/country/', AjaxSettingsCountrySearchView.as_view(), name = 'ajaxsettingscountrysearch'),
     


    # ajax
    path('operator/branch-operator/email/validate/',
         validateoperatoremailview, name='checkemail'),

    path('countryname/check/', CountryAjaxCheck, name='checkcountryname'),
    path('provincename/check/', ProvinceAjaxCheck, name='checkprovincename'),
    path('districtname/check/', DistrictAjaxCheck, name='checkdistrictname'),
    path('cityname/check/', CityAjaxCheck, name='checkcityname'),

    # operator customer
    path('operator/customers/list/',
         OperatorCustomersListView.as_view(), name='opcustomerslist'),
    path('operator/customers/create/',
         OperatorCustomersCreateView.as_view(), name='opcustomerscreate'),
    path('operator/customers/update/<int:pk>/',
         OperatorCustomersUpdateView.as_view(), name='opcustomersupdate'),
    path('operator/customers/change-password/<int:pk>',
         OperatorCustomersPasswordChangeView.as_view(), name='opcustomerspc'),
    path('operator/customers/detail/<int:pk>/',
         OperatorCustomersDetailView.as_view(), name='opcustomersdetail'),
    path('operator/customers/payment-list/',
         LogisticAdminLogisticsCustomerPaymentListView.as_view(), name="lalcpaymentlist"),


     # operator rider
     path('operator/deliveryperson/list/',
         OperatorDeliveryPersonListView.as_view(), name='opdeliverypersonlist'),
     path('operator/deliveryperson/create/',
         OperatorDeliveryPersonCreateView.as_view(), name='opdeliverypersoncreate'),
     path('operator/deliveryperson/detail/<int:pk>/',
         OperatorDeliveryPersonDetailView.as_view(), name='opdeliverypersondetail'),
     path('operator/deliveryperson/update/<int:pk>/',
         OperatorDeliveryPersonUpdateView.as_view(), name='opdeliverypersonupdate'),
     path('operator/deliveryperson/change-password/<int:pk>',
         OperatorDeliveryPersonPasswordChangeView.as_view(), name='opdeliverypersonpc'),
     



    #Customer signup/login
    path("customer/signup/", CustomerSignupView.as_view(), name="customersignup"),
    path("customer/login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("customer/logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("customer/reset-password/<email>/<token>/",
         CustomerResetPasswordView.as_view(), name="customerpr"),
    path("customer/forgot-password/",
         CustomerForgotPasswordView.as_view(), name="customerfp"),

    path("username-checker/", CustomerUsernameCheckerView.as_view(),
         name="usernamechecker"),

    
    #Operator signup/login
    path("operator/signup/",LogisticCompanySignupView.as_view(), name="logcompanysignup"),
    path("operator/login/", LogisticCompanyLoginView.as_view(), name="logcompanylogin"),
    path("operator/forgot-password/", LogisticCompanyForgotPasswordView.as_view(), name="logcompanyfp"),
    path("operator/reset-password/<email>/<token>/", LogisticCompanyResetPasswordView.as_view(), name="logcompanypr"),
    path("operator/logout/", LogoutView.as_view(), name='logout'),
    path("operator/accounts/detail/",
         OperatorAccountDetailView.as_view(), name='operatoraccount'),
         
    

]

templates/logisticstemplates/cmp/cmplaloadnotelist.html
<div id="chatscrollbottom" class="card-body" style="height: 37vh; overflow-y: scroll;">
    {% for note in notelist %}
    <p style="font-size: 1.3rem;">
        {{note.remarks}} <br>
        <span style="font-size: 1rem;">by- {{request.user.username}} {{note.created_at|timesince}} ago</span>
    </p>
    <hr>
    {% endfor %}
</div>
<div class="media-list media-separator">
    <textarea type="text" class="form-control input-success" id="notearea" rows="3" placeholder="Write a Note" style="border: 1px solid green;"></textarea>
    <button class="btn btn-success btn-sm mt-2" id="addnote" style="width: 100%;" disabled>Add a Note</button>
</div>

templates/logisticstemplates/cmp/cmplaloadshipmentlistatwarehouse.html
<style>
    .select2 input{
        height: 200px!important;
    }
    @media (max-width: 600px) {
        .select2 {
            float: center;
            margin-top: 5px;
        }
    }
    @media (min-width: 600px) {
        .select2 {
            float: right;
            margin-top: 5px;
        }
    }
</style>
<div class="table-responsive">
    <table class="table mb-0 table-fluid">
        <thead>
            <tr>
                <th><input id="selectallinputbox" type="checkbox"></th>
                <th scope="col" style="width: 25%;">Shipment ID</th>
                <th scope="col" style="width: 30%;">Sender Info</th>
                <th scope="col" style="width: 30%;">Receiver Info</th>
                <th scope="col" style="width: 10%;">Shipment Value</th>
                <th scope="col" style="width: 5%;">Action</th>
            </tr>
        </thead>
        <tbody id="load-more-data">
            <button id="assignstaff-for-delivery-shipment-btn" class="btn btn-primary btn-sm">Assign Staff For Delivery</button>
            <!-- <button id="create-shipment-bundle-btn" class="btn btn-warning btn-sm">Create a Bundle</button> -->
            <button id="print-shipment-label-btn" class="btn btn-info btn-sm">Print Shipment Label</button>
            <input type="text" class="form-control d-inline-block search-input" placeholder="Type And Press Enter" style="width: 200px; float: right;">
            <select name="city-select" id="city-filter" class="form-control d-inline-block select2">
                <option value="">All City</option>
                {% for city in citylist %}
                <option value="{{city.id}}">{{city.name}}</option>
                {% endfor %}
            </select>
            {% for shipment in shipmentlist %}
            <tr>
                <td><input data-id="{{shipment.id}}" type="checkbox"></td>
                <td>
                    <span><a href="{% url 'lmsapp:lashipmentdetail' shipment.id %}">{{shipment.tracking_code}}</a></span><br>
                    <span>{{shipment.created_at}}</span><br>
                    <span style="color: #FF4068;">{{shipment.created_at|timesince}} ago</span>
                </td>
                <td class="text-dark">
                    <span>{{shipment.sender_name}},
                        {{shipment.sender_contact_number}}
                    </span><br>
                    <span style="font-size: 1.2rem;">({{shipment.sender_address}}),</span> {{shipment.sender_city}}</span>
                </td>
                <td class="text-dark">
                    <span>{{shipment.receiver_name}},
                        {{shipment.receiver_contact_number}}
                    </span><br>
                    <span><span style="font-size: 1.2rem;">({{shipment.receiver_address}}),</span> {{shipment.receiver_city}}</span>
                </td>
                <td>Rs. {{shipment.cod_value}}</td>
                <td>
                    <!-- List -->
                    <ul class="dt-list dt-list-cm-0">
                        <!-- List Item -->
                        <li class="dt-list__item">
                            <a class="text-light-gray" href="{% url 'lmsapp:lashipmentupdate' shipment.id %}">
                                <i class="icon icon-editors "></i>
                            </a>
                        </li>
                        <!-- /list item -->
                        <!-- List Item -->
                        <li class="dt-list__item">
                            <div class="dropdown">
                                <a class="dropdown-toggle no-arrow text-light-gray"
                                   href="#" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="icon icon-horizontal-more icon-fw"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="{% url 'lmsapp:lashipmentdetail' shipment.id %}">Shipment Detail</a>
                                    <a class="dropdown-item" data-toggle="modal"
                                    data-target="#main-modal" href="{% url 'lmsapp:cmplashipmentinfo' shipment.id %}" data-remote="{% url 'lmsapp:cmplashipmentinfo' shipment.id %}">Shipment Charge Info</a>
                                </div>
                            </div>
                        </li>
                        <!-- /list item -->
                    </ul>
                    <!-- /list -->
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div id="load-more-button">
    {% if shipmentlist.has_next is True %}
    
        <!-- Pagination -->
        <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item"><a class="page-link page-link-next" data-href="?page={{ shipmentlist.next_page_number}}{% if paginate_by %}&paginate_by={{paginate_by}}{% endif %}{% if city %}&cityId={{city}}{% endif %}">Load More (Showing {{ shipmentlist.end_index }} of {{ shipmentlist.paginator.count }})</a>
                </li>
            </ul>
        </nav>
        <!-- /pagination -->
    
    {% endif %}
</div>
<script>
    $(document).ready(function () {
        $('.select2').select2();
        $('.select2').css({'width': '200px', 'margin-right': '10px'});
        $('.select2-selection').css({'height': '35px'});
    });
</script>

templates/logisticstemplates/cmp/cmplaloadshipmentlistcanceled.html
<div class="table-responsive">
    <table class="table mb-0 table-fluid">
        <thead>
            <tr>
                <th><input id="icon-checkbox-1" type="checkbox"></th>
                <th scope="col" style="width: 25%;">Shipment ID</th>
                <th scope="col" style="width: 30%;">Sender Info</th>
                <th scope="col" style="width: 30%;">Receiver Info</th>
                <th scope="col" style="width: 10%;">Shipment Value</th>
                <th scope="col" style="width: 5%;">Action</th>
            </tr>
        </thead>
        <tbody id="load-more-data">
            <input type="text" class="form-control d-inline-block search-input" placeholder="Type And Press Enter" style="width: 200px; float: right;">
            {% for shipment in shipmentlist %}
            <tr>
                <td><input id="icon-checkbox-1" type="checkbox"></td>
                <td>
                    <span><a href="{% url 'lmsapp:lashipmentdetail' shipment.id %}">{{shipment.tracking_code}}</a></span><br>
                    <span>{{shipment.created_at}}</span><br>
                    <span style="color: #FF4068;">{{shipment.created_at|timesince}} ago</span>
                </td>
                <td class="text-dark">
                    <span>{{shipment.sender_name}},
                        {{shipment.sender_contact_number}}
                    </span><br>
                    <span style="font-size: 1.2rem;">({{shipment.sender_address}}),</span> {{shipment.sender_city}}</span>
                </td>
                <td class="text-dark">
                    <span>{{shipment.receiver_name}},
                        {{shipment.receiver_contact_number}}
                    </span><br>
                    <span><span style="font-size: 1.2rem;">({{shipment.receiver_address}}),</span> {{shipment.receiver_city}}</span>
                </td>
                <td>Rs. {{shipment.cod_value}}</td>
                <td>
                    <!-- List -->
                    <ul class="dt-list dt-list-cm-0">
                        <!-- List Item -->
                        <li class="dt-list__item">
                            <a class="text-light-gray" href="{% url 'lmsapp:lashipmentupdate' shipment.id %}">
                                <i class="icon icon-editors "></i>
                            </a>
                        </li>
                        <!-- /list item -->
                        <!-- List Item -->
                        <li class="dt-list__item">
                            <div class="dropdown">
                                <a class="dropdown-toggle no-arrow text-light-gray"
                                   href="#" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="icon icon-horizontal-more icon-fw"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="{% url 'lmsapp:lashipmentdetail' shipment.id %}">Shipment Detail</a>
                                    <a class="dropdown-item" data-toggle="modal"
                                    data-target="#main-modal" href="{% url 'lmsapp:cmplashipmentinfo' shipment.id %}" data-remote="{% url 'lmsapp:cmplashipmentinfo' shipment.id %}">Shipment Charge Info</a>
                                </div>
                            </div>
                        </li>
                        <!-- /list item -->
                    </ul>
                    <!-- /list -->
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div id="load-more-button">
    {% if shipmentlist.has_next is True %}
    
        <!-- Pagination -->
        <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item"><a class="page-link page-link-next" data-href="?page={{ shipmentlist.next_page_number}}{% if paginate_by %}&paginate_by={{paginate_by}}{% endif %}">Load More (Showing {{ shipmentlist.end_index }} of {{ shipmentlist.paginator.count }})</a>
                </li>
            </ul>
        </nav>
        <!-- /pagination -->
    
    {% endif %}
</div>