lmsapp/urls.py
from django.urls import path
from .views import *
from . import views


app_name = "lmsapp"
urlpatterns = [

    # 1 System Operator Views


    # 2 Logistics Operator Views
    path("operator/dashboard/", LogisticsAdminHomeView.as_view(), name="lahome"),
    path("operator/shipments/list/",
         LogisticsAdminShipmentListView.as_view(), name="lashipmentlist"),
    path("operator/shipments/new-create/",
         LogisticsAdminShipmentCreateView.as_view(), name="lashipmentcreate"),
    path("operator/shipments/update-<int:pk>/",
         LogisticsAdminShipmentUpdateView.as_view(), name="lashipmentupdate"),
    path("operator/shipments/detail-<int:pk>/",
         LogisticsAdminShipmentDetailView.as_view(), name="lashipmentdetail"),

    path("operator/bundles/list/",
         LogisticsAdminBundleListView.as_view(), name="labundlelist"),
    path("operator/bundle/update-<int:pk>/",
         LogisticsAdminBundleUpdateView.as_view(), name="labundleupdate"),
    path("operator/bundles/incoming-list/",
         LogisticsAdminIncomingBundleListView.as_view(), name="laincomingbundlelist"),

    path("operator/bundles/cmp/laloadbundlelist/",
         CmpLogisticsAdminLoadBundleListView.as_view(), name="cmplaloadbundlelist"),
    path("operator/bundles/cmp/labundleinfo-<int:pk>/",
         CmpLogisitcsAdminLoadBundleInfoView.as_view(), name="cmplabundleinfo"),
    path("operator/bundles/cmp/laloadincomingbundlelist/",
         CmpLogisticsAdminLoadIncomingBundleListView.as_view(), name="cmplaloadincomingbundlelist"),

    path("operator/bundles/ajax/labundlechangestatus/",
         AjaxLogisticsAdminBundleChangeStatusView.as_view(), name="ajaxlabundlechangestatus"),
    path("operator/shipments-bundle/ajax/shipment-charge/<attribute>/update/",
         AjaxLogisticsAdminShipmentBundleShipmentChargeUpdateView.as_view(), name="ajaxlashipmentbundleshipmentchargeupdate"),
    path("operator/shipments/ajax/labundlechangestatus/",
         AjaxLogisticsAdminBundleShipmentChangeStatusView.as_view(), name="ajaxlabundleshipmentchangestatus"),
    # shipment bundle create modal
    path("operator/shipment-bundle/ajax/destination-option-modal/",
         AjaxLogisticsAdminShipmentBundleDestinationOptionModalView.as_view(), name="ajaxlashipmentbundledestinationoptionmodal"),

    path("operator/shipments/cmp/laloadshipmentlist/",
         CmpLogisticsAdminLoadShipmentListView.as_view(), name="cmplaloadshipmentlist"),
    path("operator/shipments/cmp/lashipmentinfo-<int:pk>/",
         CmpLogisitcsAdminLoadShipmentInfoView.as_view(), name="cmplashipmentinfo"),
    path("operator/shipments/cmp/laloadenquirylist/",
         CmpLogisticsAdminLoadEnquiryListView.as_view(), name="cmplaloadenquirylist"),

    path("operator/shipments/ajax/lashipmentactivity-<int:pk>/",
         AjaxLogisticsAdminShipmentActivityCreateView.as_view(), name="ajaxlashipmentactivitycreate"),
    path("operator/shipments/ajax/lashipmentchangestatus/",
         AjaxLogisticsAdminShipmentChangeStatusView.as_view(), name="ajaxlashipmentchangestatus"),
    path("operator/shipments/ajax/shipment-charge/<attribute>/update/",
         AjaxLogisticsAdminShipmentChargeUpdateView.as_view(), name="ajaxlashipmentchargeupdate"),

    path("operator/shipment/shipping-label/<int:pk>/",
         LogisticAdminShipmentShippingLabelView.as_view(), name="lashipmentshippinglabel"),
    # path("operator/shipment/bulk-shipping-label/",
    #      LogisticAdminShipmentBulkShippingLabelView.as_view(), name-"lashipmentbulkshipmentlabel"),
    path("operator/shipment/bulk-shipping-label/",
         LogisticAdminShipmentShippingLabelView.as_view(), name="lashipmentbulkshipmentlabel"),

    path("settings/", LogisticsAdminSettingsView.as_view(), name="lasettings"),

    path('operator/branch-operator/customer/ticket/list/',
         CustomerSupportTicketListView.as_view(), name='operatorcustomerticketlist'),

    path('operator/branch-operator/customer/ticket/detail/<int:pk>/',
         CustomerSupportTicketDetailView.as_view(), name='operatorcustomerticketdetail'),

    path('operator/branch-operator/customer/ticket/update/<int:pk>/',
         CustomerSupportTicketUpdateView.as_view(), name='operatorcustomerticketupdate'),

    path('operator/branch-operator/customer/ticket/support/ajax/<int:pk>/',
         CustomerSupportTicketAjaxView.as_view(), name='ticketraiseajax'),

    path('operator/branch-operator/customer/ticket/status/list/',
         CustomerTicketNoticeStatusList.as_view(), name='ticketstatuslist'),
    path('operator/branch-operator/customer/message/status/list/',
         CustomerTicketFollowUpdMessageStatusList.as_view(), name='messagestatuslist'),
    # path('operator/branch-operator/customer/ticket/support/ajax/list/', CustomerSupportTicketListAjaxView.as_view(), name='operatorcustomerticketajaxlist'),

    path('operator/branch-operator/customer/notice/list/',
         LogisticsNoticeListView.as_view(), name='opnoticelist'),
    path('operator/branch-operator/customer/notice/create/',
         LogisticsNoticeCreateView.as_view(), name='opnoticecreate'),
    path('operator/branch-operator/customer/notice/update/<int:pk>/',
         LogisticsNoticeUpdateView.as_view(), name='opnoticeupdate'),
    path('operator/branch-operator/customer/notice/detail/<int:pk>/',
         LogisticsNoticeDetailView.as_view(), name='opnoticedetail'),

    path('operator/logistic-customer/ajax/list/',
         AjaxLALogisticCustomerListView.as_view(), name="ajaxlalogisticcustomerlist"),

    path('operator/logistic-customer/<int:pk>/shipments-list/payment/',
         LogisticsAdminLogisticsCustomerShipmentPaymentListView.as_view(), name="lalcshipmentpaymentlist"),
    

    path('operator/logistic-customer/quotation/request/list/',
         LogisticsCustomerRequestQuotationFromBranch.as_view(), name="customerrequestquotation"),
    path('operator/logistic-customer/quotation/request/approved/list/',
         LogisticsCustomerRequestQuotationFromBranchApproved.as_view(), name="customerrequestquotationapproved"),
    path('operator/logistic-customer/signed/quotation/request/approved/list/',
         LogisticsCustomerSignedRequestQuotationFromBranchApproved.as_view(), name="customerrequestsignedquotationapproved"),
    path('operator/logistic-customer/quotation/request/create/<int:pk>/',
         LogisticsCustomerRequestQuotationFromBranchCreateView.as_view(), name="customerrequestquotationcreate"),
    path('operator/logistic-customer/quotation/request/update/<int:pk>/',
         LogisticsCustomerRequestQuotationFromBranchUpdateView.as_view(), name="customerrequestquotationupdate"),
    path('operator/logistic-customer/quotation/request/detail/<int:pk>/',
         LogisticsCustomerRequestQuotationFromBranchDetail.as_view(), name="customerrequestquotationdetail"),

    path('operator/logistic-customer/quotation/request/ajax/',
         LogisticsCustomerRequestQuotationFromBranchApprovedAjaxView.as_view(), name="customerrequestquotationajax"),
    path('operator/logistic-customer/quotation/request/ajax2/',
         LogisticsCustomerRequestQuotationFromBranchApprovedAjaxView2.as_view(), name="customerrequestquotationajax2"),

    # Customer Payment
    path('operator/payment/lc-<int:pk>-payment/',
         LogisticAdminLogisticsCustomerShipmentPaymentView.as_view(), name="lalcshipmentpayment"),
    path('operator/logistic-customer/shipment-process-payment/',
         LogisticsAdminLogisticsCustomerShipmentProcessPaymentView.as_view(), name="lalcshipmentprocesspayment"),
    path('operator/customer-payment/list/',
         OperatorCustomerPaymentListView.as_view(), name="opcustomerpaymentlist"),
    path('operator/customer-payment/detail/<int:pk>/',
         OperatorCustomerPaymentDetailView.as_view(), name="opcustomerpaymentdetail"),
    path('operator/logistic-customer/shipment-process-payment/print/',
         LogisticAdminLogisticsCustomerShipmentProcessPaymentPrintView.as_view(), name="lalcshipmentprocesspaymentprint"),
    path('operator/logistic-customer/shipment-process-payment/download/',           
         LogisticAdminLogisticsCustomerShipmentProcessPaymentDownloadView.as_view(), name="lalcshipmentprocesspaymentdownload"),

    # logistics admin sidebar
    path("operator/cmp/sidebardetail/",
         CmpLogisticsAdminLoadSidebarView.as_view(), name="cmplasidebardetail"),


    # --------------------------------------------
    # Logistics customer panel urls
    # 3 Logistic Customers Views

    path("customer/dashboard/",
         LogisticsCustomerDashboardView.as_view(), name="lcdashboard"),
     path("customer/profile/", LogisticCustomerProfileView.as_view(), name="customerprofileview"),
     path("customer/profile/update/<int:pk>/", LogisticCustomerProfileUpdateView.as_view(), name="customerprofilupdate"),

    # shipment management
    path('customer/shipment-list/', CustomerShipmentListView.as_view(),
         name='customershipmentlist'),
    path('customer/shipment-<int:pk>-detail/',
         CustomerShipmentDetailView.as_view(), name='customershipmentdetail'),
    path('customer/request-shipment/',
         CustomerShipmentCreateView.as_view(), name='customershipmentcreate'),
    path('customer/get-filtered-branches/',
         CustomerGetFilteredLogisticsView.as_view(), name='getfilteredlogistics'),
    path('customer/logsitic-company/cost/',
         CustomerLogisticsBranchCost.as_view(), name='branchcost'),


    path('customer/bulk-shipment/upload/',
         CustomerBulkShipmentUpload.as_view(), name='customerbulkshipmentupload'),

    # tickets
    path('customer/support/ticket/list/',
         CustomerSupportTicketRaiseListView.as_view(), name='customerticketlist'),
    path('customer/support/ticket/create/',
         CustomerSupportTicketCreateView.as_view(), name='customerticketcreate'),
    path('customer/support/ticket/detail/<int:pk>/',
         CustomerSupportTicketDetail.as_view(), name='customerticketdetail'),

lmsproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from lcapiapp.views import *

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("umapp.urls")),
    path('', include("lmsapp.urls")),

    path('api/v1/customer/', include("lcapiapp.urls")),
    path('api/v1/logistics/', include("lbapiapp.urls")),

    # path('password-reset/check/token/<uidb64>/<token>/',
    #      PasswordTokenCheckAPI.as_view(), name='token-check'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

umapp/urls.py
from django.urls import path, include
from .views import *

app_name = "umapp"
urlpatterns = [
    
#     path("operator/reset-password/",
#          LogisticsAdminResetPasswordView.as_view(), name="laresetpassword"),
    # path("operator/login/", LogisticsAdminLoginView.as_view(),
    #      name="logisticsadminlogin"),
    


    # Country
    path('operator/country/create',
         CountryCreateView.as_view(), name='countrycreate'),
    path('operator/country/<int:pk>/edit/',
         CountryUpdateView.as_view(), name='countryedit'),


    # province
    # path('operator/province/list/', ProvinceView.as_view(), name='provincelist'),
    path('operator/province/create/',
         ProvinceCreateView.as_view(), name='provincecreate'),
    path('operator/province/<int:pk>/edit/',
         ProvinceUpdateView.as_view(), name='provinceedit'),
    path('operator/province/delete/<int:pk>/',
         ProvinceDelete.as_view(), name='provincedelete'),


    # #District url
    # path('operator/district/list/', DistrictView.as_view(), name="districtlist"),
    path('operator/district/create/',
         DistrictCreateView.as_view(), name="districtcreate"),
    path('operator/district/update/<int:pk>/',
         DistrictUpdate.as_view(), name="districtedit"),


    # #City Url
    # path('operator/cities/list/',CityView.as_view(), name='citylist'),
    path('operator/cities/create/', CityCreateView.as_view(), name='citycreate'),
    path('operator/city/update/<int:pk>/',
         CityUpdateView.as_view(), name="cityedit"),

     path("initial-setup/", InitialSetupView.as_view(), name="initialsetup"),


    # branchoperator
    path('operator/branch-operator/list',
         BranchOperatorListView.as_view(), name='operatorlist'),
    path('operator/branch-operator/create',
         BranchOperatorCreateView.as_view(), name='operatorcreate'),
    path('operator/branch-operator/update/<int:pk>',
         BranchOperatorUpdateView.as_view(), name='operatorupdate'),


    # Branch operator password change
    path('operator/branch-operator/pass/change/<int:pk>/',
         BranchOperatorPasswordChangeView.as_view(), name='operatorpasschange'),



    # Shipping Zone
    path('operator/branch-operator/shipping/zone/',
         LogisticBranchShippingListZoneView.as_view(), name='shippinglist'),
    path('operator/branch-operator/shipping/zone/create',
         LogisticBranchShippingZoneCreateView.as_view(), name='shippingzonecreate'),
    path('operator/branch-operator/shipping/zone/update/<int:pk>/',
         LogisticBranchShippingZoneUpdateView.as_view(), name='shippingupdate'),
    path('operator/branch-operator/shipping/zone/detail/<int:pk>/',
         logisticsBranchShippingZoneDetailView.as_view(), name='shippingdetail'),
     path('operator/ajax/serch/city/', AjaxCitySearchView.as_view(), name = 'ajaxcitysearach'),
     # path('operator/ajax/list/city/', AjaxCitySearchListView.as_view(), name = 'ajaxcitysearchlist'),


    # DeliveryType/

    path('operator/branch-operator/create/deliverytype/',
         DeliveryTypeView.as_view(), name='deliverytype'),
    path('operator/branch-operator/update/deliverytype/<int:pk>/',
         DeliveryTypeUpdateView.as_view(), name='deliverytypeupdate'),

     #settings
    path('operator/branch-operator/settings/',
         SettingView.as_view(), name='settings'),
     path('operator/branch-operator/settings/ajax/search/city/', AjaxSettingsCitySearchView.as_view(), name = 'ajaxsettingscitysearch'),
     # path('operator/branch-operator/settings/ajax/search/district/', AjaxSettingsDistrictSearchView.as_view(), name = 'ajaxsettingsdistrictsearch'),
     # path('operator/branch-operator/settings/ajax/search/province/', AjaxSettingsProvinceSearchView.as_view(), name = 'ajaxsettingsprovincesearch'),
     # path('operator/branch-operator/settings/ajax/search/country/', AjaxSettingsCountrySearchView.as_view(), name = 'ajaxsettingscountrysearch'),
     


    # ajax
    path('operator/branch-operator/email/validate/',
         validateoperatoremailview, name='checkemail'),

    path('countryname/check/', CountryAjaxCheck, name='checkcountryname'),
    path('provincename/check/', ProvinceAjaxCheck, name='checkprovincename'),
    path('districtname/check/', DistrictAjaxCheck, name='checkdistrictname'),
    path('cityname/check/', CityAjaxCheck, name='checkcityname'),

    # operator customer
    path('operator/customers/list/',
         OperatorCustomersListView.as_view(), name='opcustomerslist'),
    path('operator/customers/create/',
         OperatorCustomersCreateView.as_view(), name='opcustomerscreate'),
    path('operator/customers/update/<int:pk>/',
         OperatorCustomersUpdateView.as_view(), name='opcustomersupdate'),
    path('operator/customers/change-password/<int:pk>',
         OperatorCustomersPasswordChangeView.as_view(), name='opcustomerspc'),
    path('operator/customers/detail/<int:pk>/',
         OperatorCustomersDetailView.as_view(), name='opcustomersdetail'),
    path('operator/customers/payment-list/',
         LogisticAdminLogisticsCustomerPaymentListView.as_view(), name="lalcpaymentlist"),


     # operator rider
     path('operator/deliveryperson/list/',
         OperatorDeliveryPersonListView.as_view(), name='opdeliverypersonlist'),
     path('operator/deliveryperson/create/',
         OperatorDeliveryPersonCreateView.as_view(), name='opdeliverypersoncreate'),
     path('operator/deliveryperson/detail/<int:pk>/',
         OperatorDeliveryPersonDetailView.as_view(), name='opdeliverypersondetail'),
     path('operator/deliveryperson/update/<int:pk>/',
         OperatorDeliveryPersonUpdateView.as_view(), name='opdeliverypersonupdate'),
     path('operator/deliveryperson/change-password/<int:pk>',
         OperatorDeliveryPersonPasswordChangeView.as_view(), name='opdeliverypersonpc'),
     



    #Customer signup/login
    path("customer/signup/", CustomerSignupView.as_view(), name="customersignup"),
    path("customer/login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("customer/logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("customer/reset-password/<email>/<token>/",
         CustomerResetPasswordView.as_view(), name="customerpr"),
    path("customer/forgot-password/",
         CustomerForgotPasswordView.as_view(), name="customerfp"),

    path("username-checker/", CustomerUsernameCheckerView.as_view(),
         name="usernamechecker"),

    
    #Operator signup/login
    path("operator/signup/",LogisticCompanySignupView.as_view(), name="logcompanysignup"),
    path("operator/login/", LogisticCompanyLoginView.as_view(), name="logcompanylogin"),
    path("operator/forgot-password/", LogisticCompanyForgotPasswordView.as_view(), name="logcompanyfp"),
    path("operator/reset-password/<email>/<token>/", LogisticCompanyResetPasswordView.as_view(), name="logcompanypr"),
    path("operator/logout/", LogoutView.as_view(), name='logout'),
    path("operator/accounts/detail/",
         OperatorAccountDetailView.as_view(), name='operatoraccount'),
         
    

]

templates/logisticstemplates/settings/ajaxcountrysearchlist.html
  <div class="table-responsive">
    <table class="table mb-0 table-fluid">
        <thead>
            <tr>
              <th scope="col">Sn.</th>
              <th scope="col">Country</th>
              <th scope="col">country Slug</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
        <tbody id="load-more-data">
            <a
            class="btn btn-primary pull-right"
            data-toggle="modal"
            data-target="#create-modal"
            data-remote="{% url 'umapp:countrycreate' %}"
            style="
              color: white;
            "
            >Create Country</a>
            <input type="text" class="form-control d-inline-block search-input" placeholder="Type And Press Enter" style="width: 200px; float: right;">
            {% for country in settingslist %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{country.name}}</td>
                <td>{{country.slug}}</td>
                <td>
                <a href="" data-toggle="modal" data-target="#update-modal" data-remote="{% url 'umapp:countryedit' country.id %}" class="btn-sm btn-warning" title="Update">Update</a>
                {% comment %} <a href="" data-toggle="modal" data-target="#delete-modal" data-remote="{% url 'umapp:provincedelete' prov.id %}" class="btn-sm btn-danger ">delete</a>   {% endcomment %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </div>
  <div id="load-more-button">
    {% if settingslist.has_next is True %}
    
        <!-- Pagination -->
        <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item"><a class="page-link page-link-next" data-href="?page={{ settingslist.next_page_number}}{% if paginate_by %}&paginate_by={{paginate_by}}{% endif %}">Load More (Showing {{ settingslist.end_index }} of {{ settingslist.paginator.count }})</a>
                </li>
            </ul>
        </nav>
        <!-- /pagination -->
    
    {% endif %}
  </div>
  
  <script>
    $(document).ready(function () {
        $('.select2').select2();
        $('.select2').css({'width': '200px'});
    });
  </script>

templates/logisticstemplates/settings/branchoperatorlist.html
{% extends 'logisticstemplates/logisticsadminbase.html' %}
{% load static %}
{% block title %}Operators{% endblock %}
{% block operator %}active-title{% endblock %}


{% block content %}
<div class="dt-content-wrapper">
  <div class="dt-content">
    <div class="row">

      <div class="col-xl-12">

      <div class="card">
          <div class="row">
            <div class="col-md-12">
              <span>
                 <div class="d-flex align-items-center justify-content-between mb-4">
                      <h3 class="dt-card__title" id="status-title"></h3>
                      <a href='{% url 'umapp:operatorcreate' %}' class="d-inline-block mr-10 mt-10"><i
                          class="icon icon-circle-add-o mr-4"></i>Add Operator</a>
                  </div>
              <span class='ml-4'>
                  search:  <input type="text" style='margin:5px;' id="operatorsearchinput" placeholder="Search for names.." title="Type in a name">
              </span>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Sn.</th>
                    <th scope="col">Operator Type</th>
                    <th scope="col">Full Name</th>
                    <th scope="col">Mobile</th>
                    <th scope="col">Address City</th>
                    {% comment %} <th scope="col">Coverage Cities</th>
                    <th scope="col">Connected Branches</th> {% endcomment %}
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for op in operators %}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{op.operator_type}}</td>
                    <td>{{op.full_name}}</td>
                    <td>{{op.mobile}}</td>
                    <td>{{op.address_city}}</td>
                    {% comment %} <td>
                    {% for c in op.coverage_cities.all %}
                    {{c.name}}<br>
                    {% endfor %}
                    </td>
                    <td>
                    {% for cb in op.connected_branches.all %}
                      {{cb.branch_address}}<br>
                    {% endfor %}
                    </td> {% endcomment %}
                    <td>
                    {% if op.operator_type == 'SuperAdmin' %}
                    <p></p>
                    {% else %}
                    <a href="{% url 'umapp:operatorpasschange' op.id %}" class="btn-sm btn-warning" title="change-pass" target='_blank'><i class="fas fa-key"></i></a>
                    {% endif %}
                    <a href="{% url 'umapp:operatorupdate' op.id %}" class="btn-sm btn-primary "><i class="fas fa-pencil"></i></a>  
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          </div>
          </div>
        </div>
  </div>
</div>



<!-- Modal -->

{% endblock  %}

</div>

{% block js %}
<script>
$(document).ready(function(){
  $("#operatorsearchinput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $(".table tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>


{% endblock  %}

templates/logisticstemplates/settings/citycreate.html
<div class="modal-header">
	<h5 class="modal-title" id="mySmallModalLabel">Create City ?</h5>
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<form method="POST" action="{% url 'umapp:citycreate' %}">
	{% csrf_token %}
	<div class="modal-body">
    <div class="row" style="margin:10px;">
        <div class="col-md-4">
          <label for="">City</label>
        </div>
        <div class="col-md-8" >
          {{form.name}}
        </div>
        </div>

        <div class="row" style="margin:10px;">
        <div class="col-md-4">
          <label for="">District</label>
        </div>
        <div class="col-md-8">
          {{form.district}}
        </div>
        </div>

        <span style="visibility:hidden;"><div class="row" style="margin:10px;">
        <div class="col-md-4">
          <label for="">Slug</label>
        </div>
        <div class="col-md-8">
          {{form.slug}}
        </div>
        </div>
        </span>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-warning text-left" data-dismiss="modal">Close</button>
		<button class="btn btn-primary text-left" id='city-btn'>Save</button>
	</div>
</form>


{% block js %}
<script>
	$("#city-name").on('keyup', function(){
		var title = $(this).val();
		title = title.toLowerCase();
		title = title.replace(/[^a-zA-Z0-9]+/g,"-",);
		$("#city-slug").val(title + "-city");
	});
</script>


<script>
$(document).ready(function(){
$('#city-name').on('change', function(event){
  var city_name = $('#city-name').val();
  if (city_name == ''){
    console.log('empty')
  }else{
  $.ajax({
    url: '{% url "umapp:checkcityname" %}',
    data:{
      'city_name':city_name
    },
    dataType:"json",
    success:function(data){
      if (data.data.msg=='city available'){
        alert(data.data.msg)
        $('#city-name').val(data.data.name)
        $('#city-btn').prop("disabled",false);
      }else{
        alert(data.data.msg)
        $('#city-name').val(data.data.name)
        $('#city-btn').prop("disabled",true);
      }
    }
  });
  };
});
});

</script>

{% endblock  %}

templates/logisticstemplates/settings/districtcreate.html
<div class="modal-header">
	<h5 class="modal-title" id="mySmallModalLabel">Create District ?</h5>
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<form method="POST" action="{% url 'umapp:districtcreate' %}">
	{% csrf_token %}
	<div class="modal-body">
    <div class="row" style="margin:10px;">
        <div class="col-md-4">
          <label for="">District</label>
        </div>
        <div class="col-md-8" >
          {{form.name}}
        </div>
        </div>

        <div class="row" style="margin:10px;">
        <div class="col-md-4">
          <label for="">Province</label>
        </div>
        <div class="col-md-8">
          {{form.province}}
        </div>
        </div>

        <span style="visibility:hidden;"><div class="row" style="margin:10px;">
        <div class="col-md-4">
          <label for="">Slug</label>
        </div>
        <div class="col-md-8">
          {{form.slug}}
        </div>
        </div>
        </span>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-warning text-left" data-dismiss="modal">Close</button>
		<button class="btn btn-primary text-left" id='dist-btn'>Save</button>
	</div>
</form>


{% block js %}
<script>
	$("#dist-name").on('keyup', function(){
		var title = $(this).val();
		title = title.toLowerCase();
		title = title.replace(/[^a-zA-Z0-9]+/g,"-",);
		$("#dist-slug").val(title + "-district");
	});
</script>


<script>
$(document).ready(function(){
$('#dist-name').on('change', function(event){
  var district_name = $('#dist-name').val();
  if(district_name == ''){
    console.log('empty')
  }else{
  $.ajax({
    url: '{% url "umapp:checkdistrictname" %}',
    data:{
      'district_name':district_name
    },
    dataType:"json",
    success:function(data){
      if (data.data.msg=='district available'){
        alert(data.data.msg)
        $('#dist-name').val(data.data.name)
        $('#dist-btn').prop("disabled",false);
      }else{
        alert(data.data.msg)
        $('#dist-name').val(data.data.name)
        $('#dist-btn').prop("disabled",true);
      }
    }
  });
  };
});
});

</script>

{% endblock  %}